Local model support
abcsys/libem pull request #30
Opened 2024-07-01 17:04 UTC by Char15Xu

Added local model support for apple silicon devices

2024-07-02 01:56 UTC, zenodflow requested changes
@Char15Xu nice work! Could we add an examples/local.py to showcase the libem.match with local model?

Use the libem.calibrate tool to set the model to llama3

2024-07-02 01:56 UTC, zenodflow commented on libem/core/model.py
> +    import time
Make it to top import

2024-07-02 01:56 UTC, zenodflow commented on libem/core/model.py
> +    if not tools:
If the current local model does not support tool use, but tools are provided, let's raise a new ToolUseUnsupported error

2024-07-02 01:56 UTC, zenodflow commented on libem/parameter.py
> +    default="llama3",
Make default gpt-4o and add llama3 in options

2024-07-02 16:44 UTC, Char15Xu commented
Added the local.py file to showcase with local model, fixed all three issues in the comments.

2024-07-02 17:42 UTC, zenodflow reviewed
Lgtm. Only minor stylish comments and we're good to go! Nice work @Char15Xu.

2024-07-02 17:42 UTC, zenodflow commented on libem/core/model.py
> +        model_path = "mlx-community/Meta-Llama-3-8B-Instruct-4bit"
Since there is this dependency, I think we should add a Makefile entry to help users to prepare this?

2024-07-02 17:42 UTC, zenodflow commented on libem/core/model.py
> +    else:
Make this:

`if tools: .. else: ..`

2024-07-02 17:42 UTC, zenodflow commented on examples/local.py
> +def positive():
This is cool! Could you add a `make local` to run this example?

2024-07-03 03:21 UTC, Char15Xu commented on libem/core/model.py
> +        model_path = "mlx-community/Meta-Llama-3-8B-Instruct-4bit"
mlx-lm is integrated with huggingface, so properly installing mlx and mlx-lm packages allows the load() function to download the model automatically.

2024-07-03 03:23 UTC, Char15Xu commented on libem/core/model.py
> +    else:
do you mean `if not tools: ... else: ...`

2024-07-03 15:35 UTC, zenodflow commented on libem/core/model.py
> +    else:
If tools: raise ...
else: ...

2024-07-03 20:28 UTC, zenodflow approved these changes

2024-07-03 20:28 UTC, merged

2024-07-03 20:39 UTC, zenodflow commented
@Char15Xu, could you push this to a `feat-local` branch?

2024-07-03 20:44 UTC, zenodflow commented
The `core/model.py` needs to handle different platforms. One possibility is to put the mlx dependency in a separate `lite` directory or a `libem-lite` repo.

2024-07-04 03:46 UTC, Char15Xu commented
should i switch back to llama.cpp?

2024-07-06 00:10 UTC, zenodflow commented
For apple silicon we can use mlx and then the other platforms for llama.cpp