feat: async model call and match
abcsys/libem pull request #37
Opened 2024-07-08 23:21 UTC by daiwaid

2024-07-09 23:04 UTC, daiwaid commented
| Batch Size | F1    | Runtime Latency | Per Pair Latency | Cost |
|:----------:|:-----:|:---------------:|:----------------:|:----:|
| 1          | 94.37 | 14.44           | 2.44             | 1.20 |
| 4          | 93.78 | 3.65            | 0.41             | 1.06 |
| 16         | 94.06 | 11.60           | 0.15             | 1.01 |
| 64         | 94.86 | 11.98           | 0.12             | 0.99 |
| 128        | 94.54 | 22.32           | 0.11             | 0.99 |
| 256        | 93.43 | 32.93           | 0.10             | 0.99 |
| 512        | 70.87 | 74.44           | 0.08             | 0.95 |

2024-07-10 00:56 UTC, zenodflow commented
> Batch Size	F1	Runtime Latency	Per Pair Latency	Cost
> 1	94.37	14.44	2.44	1.20
> 4	93.78	3.65	0.41	1.06
> 16	94.06	11.60	0.15	1.01
> 64	94.86	11.98	0.12	0.99
> 128	94.54	22.32	0.11	0.99
> 256	93.43	32.93	0.10	0.99
> 512	70.87	74.44	0.08	0.95

Interestingly, the F1 has a sharp drop at 512.

2024-07-10 01:29 UTC, daiwaid commented on libem/match/function.py
> +    if len(left) <= parameter.batch_size():
This is for a bit of performance speed up (if only 1 batch, don't need to run the _create_batches() code and don't need a progress bar) and to allow for the "detailed mode" in benchmark where entities and predictions are printed as they are matched.

2024-07-10 05:04 UTC, zenodflow commented on benchmark/util.py
> +        'runtime_latency': total_time,
why not just `latency`?

2024-07-10 05:07 UTC, zenodflow commented on benchmark/util.py
> +        if args.info or args.debug:
this is very confusing

2024-07-10 05:08 UTC, zenodflow commented on benchmark/util.py
> +        if args.info or args.debug:
why no async relate to args.info and args.debug

2024-07-10 05:08 UTC, zenodflow commented on benchmark/util.py
> +                    batches.append((batch_index,
why the batch preparation code is here?

2024-07-10 05:10 UTC, zenodflow commented on benchmark/util.py
> -                num_retries = 0
revert to old

2024-07-10 05:10 UTC, zenodflow commented on benchmark/util.py
> +                    batches.append((batch_index,
revert to the original one

2024-07-10 05:11 UTC, zenodflow commented on benchmark/util.py
> +                for i, left, right, label in batches:
this is client code, it should not have the notion of batches

2024-07-10 05:11 UTC, zenodflow commented on benchmark/util.py
> -            libem.calibrate({
this is no calibration code for async?

2024-07-10 05:12 UTC, zenodflow commented on benchmark/util.py
> +        'runtime_latency': round(time.time() - start_time, 2),
this should be just `latency`

2024-07-10 05:12 UTC, zenodflow commented on examples/optimize/prompt_batch.py
> +        "libem.match.parameter.batch_size": 1,
good change - improves readability

2024-07-10 05:13 UTC, zenodflow commented on libem/constant.py
> +LIBEM_MAX_ASYNC_TASKS = 500
maybe put this to `match`. putting it here would mean globally this is the limit across all tools

2024-07-10 05:16 UTC, zenodflow commented on libem/core/model.py
>  def openai(prompt: str | list | dict,
*args **kwargs

the signature is in the later async call

2024-07-10 05:16 UTC, zenodflow commented on libem/core/model.py
> -    client = OpenAI()
not sure if the client is lazily setup, if not, pls do a factory method

2024-07-10 05:21 UTC, zenodflow commented on libem/core/util.py
> +async def throttled_async_run_all(tasks: Iterable,
such a long method name. this is just `async_run`. your signature already indicates it will throttle. 

rename `limit` to `max_concurrent`

2024-07-10 05:23 UTC, zenodflow commented on libem/interface.py
> +def match(left: Any | list[Any],
keep the specific type, not Any type.

2024-07-10 05:23 UTC, zenodflow commented on libem/interface.py
> +def info_mode():
what is the need for `info_mode`?

2024-07-10 05:25 UTC, zenodflow commented on libem/interface.py
> +def debug_mode():
`debug_mode()` sounds like a getter but here is a setter, consider `debug_on`

2024-07-10 05:25 UTC, zenodflow commented on libem/match/function.py
> +def func(left: Any | list[Any],
use specific type

2024-07-10 05:26 UTC, zenodflow commented on libem/match/function.py
> +def func(left: Any | list[Any],
if your point is that any types can be parsed in, then you must explicitly do type casting later.

otherwise, let the _client code_ do the stringification

2024-07-10 05:27 UTC, zenodflow commented on libem/match/function.py
> +            return await individual(left, right)
confusing name `individual`.

note that naming like `once` is conventional

2024-07-10 05:28 UTC, zenodflow commented on libem/match/function.py
> +    if len(left) <= parameter.batch_size():
where is the progress bar? a progress bar cannot exist inside the core match code

2024-07-10 05:29 UTC, zenodflow commented on libem/match/function.py
> +    if len(left) <= parameter.batch_size():
how much of a performance speed up? if not significant (e.g., more than 5%), let's keep it simple and dumb

2024-07-10 05:30 UTC, zenodflow commented on libem/match/function.py
> +    return batches
the original logic is clearer

2024-07-10 05:31 UTC, zenodflow requested changes
Nicely done @daiwaid -- this is impressive speed up! Just need some polishing over the implementation.

2024-07-10 05:32 UTC, zenodflow commented on libem/match/parameter.py
> -quiet = Parameter(
what was this originally for?

2024-07-10 05:33 UTC, zenodflow commented on libem/match/parameter.py
> -quiet = Parameter(
ah, I seem to recall.

the log level info / debug / warning etc. should not be directly translated to the client code as `info mode` etc.

2024-07-10 16:47 UTC, daiwaid commented on libem/match/function.py
> +    if len(left) <= parameter.batch_size():
The progress bar is in the throttled_async_run_all() function in libem.core.util

2024-07-10 17:37 UTC, daiwaid commented on benchmark/util.py
> +        'runtime_latency': total_time,
It's to differentiate this latency from the `avg_per_pair_latency` which is not `latency / len(pairs)` but the avg of all individual pair latencies. Basically `runtime_latency` takes into account the async optimization but `avg_pair_latency` doesn't.

2024-07-10 18:24 UTC, daiwaid commented on libem/constant.py
> +LIBEM_MAX_ASYNC_TASKS = 500
This constant is used in `libem.core.util`. It is meant to be a global limit. There is currently no match specific limit, but if further testing suggests that a lower limit is better then we can add one later.

2024-07-10 18:32 UTC, daiwaid commented on libem/match/function.py
> +            return await individual(left, right)
This is meant to be the opposite of `batch()`, where all pairs are matched individually.

2024-07-14 21:05 UTC, zenodflow commented on benchmark/util.py
> +        num_pairs = min(args.num_pairs, len(dataset) - start_index)
this is very confusing

2024-07-14 21:48 UTC, zenodflow commented on libem/core/model.py
> +            libem.LIBEM_CONFIG.get("OPENAI_API_KEY", "")
What if LIBEM_CONFIG has no OPENAI_API_KEY set? 

This logic should not be handled here.

2024-07-15 01:13 UTC, zenodflow commented
Asynchronous tool use will be introduced in future PRs. For this PR, async calls are used only internally within each tool

2024-07-16 09:19 UTC, zenodflow commented
https://github.com/openai/openai-python/issues/1059

Note that reusing AsyncOpenAI client can lead to misc issues. The one observed is that when the concurrency level differs > ~3, we see `openai.APIConnectionError: Connection error.` for consecutive `libem.match` calls.

2024-07-16 09:30 UTC, zenodflow commented
Module-level client also discouraged: https://github.com/openai/openai-python/issues/820

2024-07-16 10:22 UTC, zenodflow approved these changes

2024-07-16 10:26 UTC, merged