Add llama3 support on llama.cpp for non-apple silicon devices
abcsys/libem pull request #50
Opened 2024-07-20 17:09 UTC by Char15Xu

2024-07-21 16:13 UTC, zenodflow commented
@Char15Xu This is nice. Could you first rebase your branch to the current main? 

I did a bunch of updates over feat-local in https://github.com/abcsys/libem/pull/40.

2024-07-21 20:06 UTC, Char15Xu commented
it should be good now.

2024-07-22 01:26 UTC, zenodflow commented on Makefile
> +all: match match-local browse chat
I think I've removed this in #40

2024-07-22 01:26 UTC, zenodflow commented on Makefile
> +all: match match-local browse chat
Also, pls remove .DS_Store from the commit. It should be in the `.gitignore` now.

2024-07-22 01:27 UTC, zenodflow commented on Makefile
> +llama.cpp:
llama_cpp

2024-07-22 01:28 UTC, zenodflow commented on examples/local.py
> +import libem
See if this is a duplicate of https://github.com/abcsys/libem/blob/main/examples/model/llama.py

2024-07-22 01:28 UTC, zenodflow commented on libem/core/model/llama.py
> +    message_openai = (messages or []) + (context or [])
why `message_openai`? This message is in the llama.py module

2024-07-22 01:31 UTC, zenodflow commented on libem/core/model/llama.py
> +        if model == "llama3":
reverse the model serial number and the platform `if .. else` clause -- i.e. put the `if model == "llama"` the top-most if clause

2024-07-22 01:31 UTC, zenodflow commented on libem/core/model/openai.py
> +        print(response_message)
kill it

2024-07-22 01:31 UTC, zenodflow requested changes
Solid work @Char15Xu! Just some minor comments and we are good to go!

2024-07-22 19:54 UTC, Char15Xu commented on libem/core/model/llama.py
> +    message_openai = (messages or []) + (context or [])
chatCompletion in llama.cpp takes in a message of the openai format

2024-07-23 04:47 UTC, zenodflow approved these changes

2024-07-23 04:48 UTC, merged