Add anthropic model support, testing needed
abcsys/libem pull request #86
Opened 2024-08-10 01:01 UTC by Char15Xu

In this PR, we add support for claude 3.5 sonnet.

[TODO] run `make claude`  to test if current implementation work as expected.

2024-08-10 02:13 UTC, zenodflow requested changes
.DS_Store should be killed. Btw., they should be blocked by the .gitignore.

2024-08-10 02:16 UTC, zenodflow commented on Makefile
> +	python examples/model/claude.py
https://github.com/abcsys/libem/blob/eb1f549375ee083b43cf1e71f1e3db91e39e33e7/Makefile#L107

Move between gpt and llama

2024-08-10 02:17 UTC, zenodflow commented on libem/core/model/__init__.py
>          return llama.call(*args, **kwargs)
match kwargs.get("model", ""):

case ... : 
case ... : 
case _

2024-08-10 02:18 UTC, zenodflow commented on libem/core/model/claude.py
> +    if not os.environ.get("CLAUDE_API_KEY"):
Nice. This should be able to configure in the libem.cli

2024-08-20 05:57 UTC, zenodflow commented
@Char15Xu Should we add anthropic package to requirements.txt?

2024-08-20 22:09 UTC, Char15Xu commented
> @Char15Xu Should we add anthropic package to requirements.txt?

will do

2024-08-21 17:18 UTC, zenodflow commented
@Char15Xu Nice. Let me know if this is ready for another review.

2024-08-21 23:55 UTC, Char15Xu commented
@zenodflow Yes, this is ready for review

2024-08-22 03:43 UTC, zenodflow commented on cli/libem
> +        print("No input provided. Using existing API key.")
Remove this print

2024-08-22 03:43 UTC, zenodflow commented on cli/libem
>          print("No input provided. Using existing API key.")
Remove this print

2024-08-22 03:44 UTC, zenodflow approved these changes
One last nit. But overall LGTM. Nice work!

2024-08-24 22:25 UTC, Char15Xu commented
libem/optimize/price.json already include information on Claude model with the correct naming. Once the PR is approved, i will move on to test anthropic model on abt-buy dataset.

2024-08-31 00:14 UTC, merged