feat: add plotting to benchmark suites
abcsys/libem pull request #94
Opened 2024-08-26 21:34 UTC by daiwaid

#### What this PR does / why we need it:
- Add plotting to benchmark suites; use `--plot` flag to plot from the last benchmark suite run results.

#### Which issue(s) this PR addresses (if any):

Addresses #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
- Add --plot flag to the benchmark module to plot the last benchmark suite run
- New benchmark suite runs will automatically save plots to 
```

2024-08-27 00:24 UTC, zenodflow commented on benchmark/suite/gpt_35_turbo.py
> +            if file.name[26:-4].replace('35', '3.5') == name:
What is 26:-4?

2024-08-27 00:25 UTC, zenodflow commented on benchmark/suite/gpt_35_turbo.py
> +    file_name = save(df, name)
The logic here could be simplified by introducing a load call in the if args.plot?

2024-08-27 00:26 UTC, zenodflow requested changes
Nice work - just wonder if the logic can be simplified a bit.

2024-08-27 01:02 UTC, daiwaid commented on benchmark/suite/gpt_35_turbo.py
> +            if file.name[26:-4].replace('35', '3.5') == name:
to extract the suite name from the result file (remove date and .csv).

2024-08-27 01:10 UTC, daiwaid commented on benchmark/suite/gpt_35_turbo.py
> +    file_name = save(df, name)
The issue with that is we still need to pass the .csv file name into `plot()` so it can save the plot with the same name as the result. We can't generate the file name like here because in the `if args.plot` part, we are using an old result so the timestamp will be wrong if we just pass in the DataFrame.

2024-08-30 03:40 UTC, daiwaid commented
Improved version in PR #95.

2024-08-30 03:40 UTC, closed without merging