Add support for llama3.2
abcsys/libem pull request #99
Opened 2024-09-26 06:33 UTC by Char15Xu

#### What this PR does / why we need it:
In this PR, we add latest llama3.2 models for both mlx and llama.cpp framework

#### Which issue(s) this PR addresses (if any):

Addresses # None

#### Special notes for your reviewer:
Will do a benchmark on llama3.2 soon

#### Does this PR introduce a user-facing change?

```release-note
Users are now able to use 'llama3.2' as a new model input. 
```

2024-09-30 20:36 UTC, zenodflow requested changes
@Char15Xu Nice - is there benchmark results to add to the Llama.md?

2024-10-02 01:33 UTC, Char15Xu commented
full benchmark result for llama3.2 3b and partial result for llama3.2 1b have been added to the llama.md.

2024-10-02 01:34 UTC, zenodflow commented on benchmark/Llama.md
> +|:--------------:|:---------:|:------:|:-----:|:--------:|:----------------:|:-----------------:|
Good results. The 1B model has longer latency, this is a bit surprising.

2024-10-02 01:35 UTC, zenodflow approved these changes
@Char15Xu , could you add a random guess results for each dataset? I think there is a guess option of the Libem toolchain, in a future PR? 

Because some of the Llama results are quite low, we want to know how much they actually improve a random guesser.

2024-10-02 01:36 UTC, merged